### PR TITLE
JavaScript minification ability

### PR DESCRIPTION
**Pull request by nestdimon**

### CODE REVIEW

**Comment by tannerlinsley** [comment]
I believe this is automatically done with NgAnnotate in the gulpfile. Is the nz-toggle.min.js file no good?

**Comment by nestdimon** [comment]
There is no problem if someone use minified version of js file, but what if not minified file with some changes included? I personally ran into this issue with maven project because minify-maven-plugin can't automatically adapt js code for angular.

**Comment by tannerlinsley** [comment]
That makes sense. So let it be written...

**Comment by tannerlinsley** [comment]
So let it be done!

**Comment by nestdimon** [comment]
Ha ha) Thank you! :yum:

**Pull request merged**
